### ISSUE TITLE
minor midi topics

### ISSUE THREAD

**Issue by millxing** [millxing/QUENCE#21]
> midi_device.event = function(data)
>     local d = midi.to_msg(data)
>     if d.type == 'note_on' then
>         transpose = d.note - 60
>     end
> end

I don't think we need this section anymore (Actually I don't think we ever did). It looks for a root note as midi input and then transposes everything accordingly.

I know you suggested adding a separate device for each track. I'm not sure I know that would work yet. And currently the MIDI channel is just assigned by track number (e.g. Track 1 = Channel 1, Track 2 = Channel 2, etc.). So until we implement something more complicated, should we comment out midi out device and midi out channel from the parameter menu? Right now, they don't do anything.

**Comment by millxing** [comment]
I commented out both these sections and nothing changed, so I'll make this change.

**Comment by millxing** [comment]
yeah that's right. your change starts the sequence on step 2, not step 1. You could argue that it doesn't matter, because all the steps are empty to start with, but I find that as inelegant as the original fix (starting on 16). 

How about my other idea? We start with a variable that is one to start, but goes to zero after the first unpausing. But when it is equal to one, we keep the 16th LED dim so that nobody can see that we are starting with the 16th step.

**Comment by millxing** [comment]
Why did I use local_x instead of track? There must have been a reason, no?

**Comment by tildebyte** [comment]
Actually, I think *I* renamed it to 'local_x' because I was worried about it shadowing another 'x', but I wasn't entirely sure of it's function...

**Comment by tildebyte** [comment]
> but I find that as inelegant as the original fix (starting on 16).

See #22, which might be a less-inelegant compromise :D
