### ISSUE TITLE
[feat] Output to crow

### ISSUE THREAD

**Issue by tildebyte** [millxing/QUENCE#6]
NOT IT 😝 

I don't have a crow, so I won't be implementing this, but I can't think of why this wouldn't be a good idea and reasonably straightforward to implement.

**Comment by millxing** [comment]
I don't have a Crow either yet.

**Comment by justmat** [comment]
There are 4 cv outs on crow. Currently we use output 1 for note cv and output 2 for trigger out. I am thinking about changing "crow cv" to "crow cv 1/2" adding a third crow output, "crow cv 3/4" that will use the other pair of cv outs.

**Comment by millxing** [comment]
sounds good
